config/routes.rb
Rails.application.routes.draw do
  
  get "wizard/new_game", to: "wizard#game_step_0", as: "new_game_wizard"
  post "wizard/create_new_game", to: "wizard#game_step_1", as: "game_step_1"
  get "games/:id/round/:round_number", to: "games#edit_round", as: "game_edit_round"
  post "games/:id/round/:round_number", to: "games#save_round", as: "game_save_round"
  get "games/:id/recap", to: "games#recap", as: "game_recap"
  get "games/:id/compute_results", to: "games#compute_results", as: "game_compute_results"
  get "games/:id/spectator", to: "games#spectator", as: "game_spectator"
  post "games/:id/save_graph", to: "games#save_graph", as: "game_save_graph"
  post "trophies/recompute_all", to: "trophies#recalculate_all_trophies_for_all_games", as: "trophies_recompute_all"
  get "trophies/matrice", to: "trophies#matrice", as: "matrice"
  
  get "calendar", to:"games#calendar", as: "calendar"
  
  resources :performances
  get "trophies/records", to: "trophies#records_index", as: "records_index"
  resources :trophies
  resources :scores
  resources :rounds
  resources :games
  resources :players
  
  get "dashboard", to: "home#dashboard", as: "dashboard"

  root to: 'home#index'
  
  devise_for :users
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper

    def index
        # @unfinished_games=Game.where("created_at > ?", Time.now-1.day).order(:created_at).reject{|g| g.is_finished?}.last(3)
        @unfinished_games=Game.order(:created_at).reject{|g| g.is_finished?}.last(3)
    end    
    
    def dashboard
        #############
        groupcount= Performance.all.group(:player_id).count
        l=groupcount.keys.map{|pid|Player.find(pid).name}
        d=groupcount.values
        @nb_total_kf_payes=CoffeeBill.all.pluck(:nb_coffee).sum
        @perf_by_player_data = {
            datasets: [{ data: d, backgroundColor: color_array_for_stats_graphs}], 
            labels: l
        }
        @perf_by_player_options = { }
        
        #############
        @still_locked_trophies=Trophy.active.where.not(:id=>Performance.all.pluck(:trophy_id).uniq)
        l=["Trophée déjà débloqués", "Trophée jamais débloqués"]
        d=[(Trophy.active.count-@still_locked_trophies.count), @still_locked_trophies.count]
        @unlocked_trophies_data = {
            datasets: [{ data: d, backgroundColor: color_array_for_stats_graphs}], 
            labels: l
        }
        @unlocked_trophies_options = { }
        #############
        diff={}
        diff2={}
        kfbus=[]
        kfpayes=[]
        Player.all.order(:id).reject{|p| p.games.count==0}.each do |p|
            kfbus << p.games.count
            kfpayes << p.nb_payed_coffees_all_time
            diff[p.name] = p.games.count-p.nb_payed_coffees_all_time
        end
        diff2=diff
        @rentables=diff2.select{|key, val| val == diff.max_by{|k,v| v}.second}
        @pasrentables=diff2.select{|key, val| val == diff.min_by{|k,v| v}.second}
        @kf_ratio_data ={
    			labels: diff.keys,
    			datasets: [{
    				label: 'Différence : Cafés Bus - Cafés payés',
    				borderColor: "#18A2B8",
    				backgroundColor: "#18A2B8",
    				fill: false,
    				data: diff.values,
    				type: 'line'
    			}, {
    				label: 'Cafés Bus',
    				backgroundColor: "#4792DB",
    				data: kfbus
    			}, {
    				label: 'Cafés payés',
    				backgroundColor: "#915B87",
    				data: kfpayes
    			}]
    
    		}
        @kf_ratio_options = { height: 150,
            elements: {
                line: {
                    tension: 0
                }
            }
        }
        ######

        c=Game.all.order(:id).map{|g| "A #{g.players.count} joueurs"}
        c2=Hash[c.uniq.map{ |i| [i, c.count(i)] }]
        @player_by_game_data = {
            datasets: [{ data: c2.values, backgroundColor: color_array_for_stats_graphs}], 
            labels: c2.keys
        }
        @player_by_game_options = { }
        ######

        perfs=Trophy.where(:technical_name=>"victory").first.performances.map{|p| p.player.name}
        perfs2=Hash[perfs.uniq.map{ |i| [i, perfs.count(i)] }]
        @victories_by_player_data = {
            datasets: [{ data: perfs2.values, backgroundColor: color_array_for_stats_graphs}], 
            labels: perfs2.keys
        }
        @victories_by_player_options = { }
        ######
        #NBPARTIES
        history_gamescount= Result.all.group(:player_id).count
        month_gamescount= Result.all.where(:game_id=>Game.this_month).group(:player_id).count
        last_month_gamescount= Result.all.where(:game_id=>Game.last_month).group(:player_id).count
        p_array={}
        Player.all.each do |p|
          p_array[p.name]=[history_gamescount[p.id]||0 , month_gamescount[p.id]||0 , last_month_gamescount[p.id]||0]
        end
        
        p_array=p_array.sort_by{|k,v| v.first}.reverse.to_h
        # raise p_array.inspect
        
        @games_by_player_data = {
            labels: p_array.keys,
    			datasets: [{
    				label: "Nombre de parties dans l'histoire",
    				backgroundColor: "#915B87",
    				data: p_array.values.map(&:first)
    			},{
    				label: "Nombre de parties ce mois-ci",
    				backgroundColor: "#4792DB",
    				data: p_array.values.map(&:second)
    			},{
    				label: "Nombre de parties le mois dernier",
    				backgroundColor: "#18A2B8",
    				data: p_array.values.map(&:third)
    			}]
    
    		}
        @games_by_player_options ={ height: 150,
            elements: {
                line: {
                    tension: 0
                }
            },
            scales:{
                yAxes:
                    [{ticks: {
                        beginAtZero:true
                        
                    }}]
                
            }
        }
        
    end
end

app/views/home/dashboard.html.haml
-#Score.recompute_all_tmp_totals
-#Score.recompute_all_rankings

.text-center
  .card.mt-2.p-1.pt-3.bg-dark.border-dark.text-info
    %h1 
      %b 
        =fa_icon "tachometer-alt"
        Tableau de bord
  .row
    .col-sm-12.col-md-4.px-md-1.pl-md-3
      .card.mt-2.border-dark
        .card-header.bg-dark.border-dark
          .row
            .col-4
              %h2.text-info
                %b=Performance.all.count
            .col-8.pt-3.text-left
              .pt-1.text-white attributions de trophée
        .card-body{:style=>"height:350px;"}
          = chartjs_doughnut_chart @perf_by_player_data, @perf_by_player_options
          
              
    .col-sm-12.col-md-4.px-md-1
      .card.mt-2.border-dark{:style=>"height:445px;overflow:scroll;"}
        .card-header.bg-dark.border-dark
          %h2.text-white.mb-0.pt-5
            %b
              =@nb_total_kf_payes
        .card-body.bg-dark.border-dark.p-0
          %h2.text-info.mb-0
            %b
              cafés payés
              %br
              au total
    // .col-sm-12.col-md-4.px-md-1
        
    //   .card.mt-2.border-dark
    //     .card-header.bg-dark.border-dark
    //       .row
    //         .col-4
    //           %h2.text-info
    //             %b=@still_locked_trophies.count
    //         .col-8.pt-3.text-left
    //           .pt-1.text-white trophées jamais débloqués
    //     .card-body{:style=>"height:350px;overflow:scroll;"}
    //       %p
    //         -@still_locked_trophies.each do |t|
    //           =link_to t do
    //             =fa_icon 'trophy'
    //             =t.name
    //             =fa_icon 'trophy'
    //             %br

    .col-sm-12.col-md-4.px-md-1.pr-md-3
        
      .card.mt-2.border-dark
        .card-header.bg-dark.border-dark
          .row
            .col-4
              %h2.text-info
                %b=Trophy.active.count
            .col-8.pt-3.text-left
              .pt-1.text-white trophées disponibles
        .card-body{:style=>"height:350px;"}
                  
          
          
          = chartjs_doughnut_chart @unlocked_trophies_data, @unlocked_trophies_options

      
  .row
    .col-12
        
      .card.mt-2.border-dark
        .card-header.bg-dark.border-dark.text-white
          Ratio cafés
        .card-body
          
          
          
          = chartjs_bar_chart @kf_ratio_data, @kf_ratio_options

        .card-footer.bg-dark.border-dark.text-white
          .row
            .col-6
              =@rentables.count>1 ? "Joueurs les plus rentables" : "Joueur le plus rentable"
              .text-info
                %b
                  =@rentables.keys.to_sentence
                %br
                %b="+#{@rentables.values.first} cafés"
            .col-6
              =@pasrentables.count>1 ? "Joueurs les moins rentables" : "Joueur le moins rentable"
              .text-info
                %b
                  =@pasrentables.keys.to_sentence
                %br
                %b="#{@pasrentables.values.first} cafés"
            

  .row
    .col-sm-12.col-md-4.px-md-1.pl-md-3
      .card.mt-2.border-dark
        .card-header.bg-dark.border-dark
          .row
            .col-4
              %h2.text-info
                %b=Game.all.count
            .col-8.pt-3.text-left
              .pt-1.text-white parties jouées
        .card-body{:style=>"height:350px;"}
          = chartjs_doughnut_chart @player_by_game_data, @player_by_game_options
          
    .col-sm-12.col-md-4.px-md-1
      .card.mt-2.border-dark
        .card-header.bg-dark.border-dark
          .pt-1.text-white Temps moyen
        .card-body.bg-dark.border-dark.p-0{:style=>"height:95px;"}
          %h2.text-info.mb-0
            %b
              = (mean(Game.all.map{|g| g.gametime_maths})/60).round
              Minutes
        .card-header.bg-dark.border-dark
          .pt-1.text-white Partie la plus courte
        .card-body.bg-dark.border-dark.p-0{:style=>"height:94px;"}
          %h2.text-info.mb-0
            %b
              = (Game.all.map{|g| g.gametime_maths}).min/60
              Minutes
        .card-header.bg-dark.border-dark
          .pt-1.text-white Partie la plus longue
        .card-body.bg-dark.border-dark.p-0{:style=>"height:95px;"}
          %h2.text-info.mb-0
            %b
              = (Game.all.map{|g| g.gametime_maths}).max/60
              Minutes
    .col-sm-12.col-md-4.px-md-1.pr-md-3
      .card.mt-2.border-dark
        .card-header.bg-dark.border-dark
          .row
            .col-4
              %h2.text-info
                %b=Trophy.where(:technical_name=>"victory").first.performances.count
            .col-8.pt-3.text-left
              .pt-1.text-white Victoriiies
        .card-body{:style=>"height:350px;"}
          = chartjs_doughnut_chart @victories_by_player_data, @victories_by_player_options
          
  .row
    .col-12
        
      .card.mt-2.border-dark
        .card-header.bg-dark.border-dark.text-white
          Nombre de parties par joueur
        .card-body
          = chartjs_bar_chart @games_by_player_data, @games_by_player_options

app/views/home/index.html.haml
.text-center

  %br

  -if @unfinished_games.blank? 
    %p.text-white{:style=>"opacity:0.6;"}
      Aucune partie en cours   
  -else
  
    %h4.text-white
      Parties en cours :
    -@unfinished_games.each do |g|
      .card
        .card-body
          =g.title
          %br
          %small.text-muted="Créée à #{l(g.created_at.in_time_zone("Europe/Paris"), :format=>"%Hh%M")}"
          %br
          %span.text-primary="Manche #{g.rounds.order(:number).last.number}"
          %br
          %b=g.players.pluck(:name).to_sentence
          %br
          =link_to "Edition", game_edit_round_path(g, g.rounds.order(:number).last.number), :class=>"btn btn-primary", :style=>"margin-top:15px;", 'data-disable-with' => fa_icon("spinner spin ").html_safe
          =link_to "Spectateur", game_spectator_path(g), :class=>"btn btn-info", :style=>"margin-top:15px;", 'data-disable-with' => fa_icon("spinner spin ").html_safe
          %br
          .pull-right
            =link_to "Supprimer la partie", game_path(g), :method=>"delete", data: {confirm: "T'es sur?"}
      %br

  %hr
  = link_to new_game_wizard_path, :class=>"btn btn-lg btn-info", 'data-disable-with' => fa_icon("spinner spin ").html_safe do
    Nouvelle partie