config/routes.rb
Rails.application.routes.draw do
  
  get "wizard/new_game", to: "wizard#game_step_0", as: "new_game_wizard"
  post "wizard/create_new_game", to: "wizard#game_step_1", as: "game_step_1"
  get "games/:id/round/:round_number", to: "games#edit_round", as: "game_edit_round"
  post "games/:id/round/:round_number", to: "games#save_round", as: "game_save_round"
  get "games/:id/recap", to: "games#recap", as: "game_recap"
  get "games/:id/compute_results", to: "games#compute_results", as: "game_compute_results"
  get "games/:id/spectator", to: "games#spectator", as: "game_spectator"
  post "games/:id/save_graph", to: "games#save_graph", as: "game_save_graph"
  post "trophies/recompute_all", to: "trophies#recalculate_all_trophies_for_all_games", as: "trophies_recompute_all"
  get "trophies/matrice", to: "trophies#matrice", as: "matrice"
  
  get "calendar", to:"games#calendar", as: "calendar"
  
  resources :performances
  get "trophies/records", to: "trophies#records_index", as: "records_index"
  resources :trophies
  resources :scores
  resources :rounds
  resources :games
  resources :players
  
  get "dashboard", to: "home#dashboard", as: "dashboard"

  root to: 'home#index'
  
  devise_for :users
  
end

app/models/player.rb
class Player < ApplicationRecord
  has_and_belongs_to_many :games
  has_many :results
  has_many :performances
  has_many :coffee_bills
    
  def name
    return "#{self[:name]}#{self.stars}"
  end    
  
  def stars
    if self.results.try(:last).try(:ranking)==1 
      if self.results.try(:last, 2).try(:first).try(:ranking)==1 && self.games.count>1 
        if self.results.try(:last, 3).try(:first).try(:ranking)==1 && self.games.count>2 
          if self.results.try(:last, 4).try(:first).try(:ranking)==1 && self.games.count>3 
            if self.results.try(:last, 5).try(:first).try(:ranking)==1 && self.games.count>4 
              return "*****"
            else
              return "****"
            end
          else
            return "***"
          end
        else
          return "**"
        end
      else 
        return "*"
      end
    else 
      return ""
    end
  end
  
  def scores_in_game(g)
    rounds=g.rounds
    Score.where(:player=>self, :round=>rounds)
  end
  
  def nb_payed_coffees_all_time
    self.coffee_bills.pluck(:nb_coffee).sum
  end
  
  def count_trophy(t)
    Performance.where(:player=>self, :trophy=>t).count
  end
  
  
  
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player_last_game=@player.games.order(:created_at).last
    @this_month_games= @player.games.this_month
    @this_month_bills=@player.coffee_bills.where(:game=>@this_month_games)
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :avatar)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.haml
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      %ul
        - @player.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :avatar
    = f.text_field :avatar
  %br
  .row
    -animal_files=  Dir.glob("*app/assets/images/animals/*")
    -animal_files.each do |animal_file|
      -a=animal_file.split("/").last
      .col-2.border.text-center.py-3
        =image_tag "animals/#{a}", size: "60"
        %br
        =a.split(".").first
  -# %small.text-muted

  -#   anteater, buffalo-1, cow,   donkey,   hedgehog,     kangaroo, marten,   octopus, parrot,    polar-bear, rooster, sheep, turtle
  -#   bear,     buffalo,   crow,  elephant, hen,          koala,    monkey-1, ostrich, penguin-1, rabbit,     seagull, sloth, whale
  -#   beaver,   cat,       dog-1, fox,      hippopotamus, leopard,  monkey,   owl,     penguin,   racoon,     seal,    snake, zebra
  -#   boar,     chicken,   dog,   giraffe,  horse,        lion,     mouse,    panda,   pig,       rhinoceros, sheep-1, tiger
  %br/
  .actions
    = f.submit 'Enregistrer', :class=>"btn btn-primary"
  %hr

app/views/players/edit.html.haml
.card.card-body
  %h4.card-title Modification de player
  
  %p.card-text
    = render 'form'
    
  .flex-row
    = link_to 'Voir', @player
    \|
    = link_to 'Retour', players_path

app/views/players/index.html.haml
.card.card-body
  %h4.card-title.text-center Joueurs
  %p.card-text 
    .row
      - @players.each do |player|
        .col-6.text-center
          = link_to player, :class=>"card bg-dark text-white text-center py-3" do
            .text-center
              -if player.avatar.present?
                =image_tag "animals/#{player.avatar}.png", size: "40"
              -else
                =image_tag "animals/sheep-1.png", size: "40"
            .h4.mt-2.mb-0
              =player.name 
          %br
     
  
  .flex-row.text-center

    
    = link_to 'Nouveau joueur', new_player_path, :class=>"card-link btn btn-primary"

app/views/players/new.html.haml
.card.card-body
  %h4.card-title Nouveau player
  %p.card-text 

    = render 'form'


  .flex-row
    = link_to 'Retour', players_path

app/views/players/show.html.haml
.card.border-dark.mb-3
  .card-header.bg-dark.text-left.text-white
    .row
      .col-2
      .col-8.text-center
        %h2.pl-3
          .pt-3
            %b= @player.name
      .col-2.text-right
        -if @player.avatar.present?
          =image_tag "animals/#{@player.avatar}.png", size: "80"
        -else
          =image_tag "animals/sheep-1.png", size: "80"

  .card-body.p-2.bg-dark
    .row  
      .col-md-4.col-sm-12.my-1
        .card.border-info
          .card-header.bg-info.text-white
            PARTIES
          .card-body.text-center.bg-info.text-white.p-2
            .statline
              %span.h3.font-weight-bold.text-dark
                ="#{@this_month_games.count}"
              %span ce mois-ci
            .statline
              %span.h3.font-weight-bold.text-dark
                ="#{@player.games.count}"
              %span dans l'histoire

      .col-md-4.col-sm-12.my-1
        .card.border-primary
          .card-header.bg-primary.text-white
            DERNIERE PARTIE
          .card-body.text-center.bg-primary.text-white
            -if @player_last_game.nil?
              .muted{:style=>"margin-top:20px;"}
                %small.text-light
                  Aucune partie
                  %br/
                  %br/
                
            -else
              %h3
                =link_to game_recap_path(@player_last_game), :class=>"text-white" do
                  =" #{l(@player_last_game.created_at.in_time_zone("Europe/Paris"), :format=>:short)}"

            
      .col-md-4.col-sm-12.my-1
        .card.border-secondary
          .card-header.bg-secondary.text-white
            CAFES
          .card-body.text-center.bg-secondary.text-white.p-2
            .statline
              %span.h3.font-weight-bold.text-dark
                ="#{@this_month_bills.pluck(:nb_coffee).sum}"
              %span ce mois-ci
            .statline
              %span.h3.font-weight-bold.text-dark
                ="#{@player.nb_payed_coffees_all_time}"
              %span dans l'histoire
  .card-footer.bg-dark.text-white.pt-4.pb-5
    %h3.text-center.pb-3 Trophées débloqués
    .row
      
      -if @player.performances.blank?
        .col-12.text-muted.text-center.h3
          ¯\_(ツ)_/¯
      -@player.performances.group(:trophy_id).count.each do |t, count|
        -troph=Trophy.find(t)
        .col-lg-2.col-md-4.col-6.text-center.pb-2.pt-3
          -popovercontent=capture_haml do
            %br
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            =troph.description
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            %br
            %br
            =link_to "Détails", 'javascript:;', :class=>"btn btn-dark btn-sm", :onclick=>"replaceclick(this)", "data-to-href"=>trophy_path(t)
              
          -bdgclass= case troph.positive
            -when "bien" then "tbadge-12-good"
            -when "neutre" then "tbadge-12-neutral"
            -when "pasbien" then "tbadge-12-bad"
            -else ""
          -textstyle= case troph.positive
            -when "bien" then "color:LightGreen;"
            -when "neutre" then "color:lightgrey;"
            -when "pasbien" then "color:salmon;"
            -else ""
          -countstyle= case troph.positive
            -when "bien" then "background-color:LightGreen;"
            -when "neutre" then "background-color:lightgrey;"
            -when "pasbien" then "background-color:salmon;"
            -else "background-color:white;"
          .text-center
            .tbadge-12{:class=>"#{bdgclass}", :style=>"margin-left: auto;margin-right: auto;","data-html"=>"true","data-template"=>'<div class="popover text-center" role="tooltip"><div class="arrow"></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>',  "data-content" => popovercontent, "data-toggle" => "popover", "data-placement" => "top", "data-trigger" => "focus", :role => "button", :tabindex => "0"}
              .pt-2.position-sticky.text-white{:style=>"z-index: 1000;"}
                =fa_icon 'trophy 4x'
            %br
            
            %p{:style=>"#{textstyle}"}
              =troph.name
              -if count>1
                %span.badge.text-dark{:style=>"#{countstyle}"}=count
  
.flex-row
  = link_to 'Retour', players_path, :class=>"card-link btn btn-secondary"

  = link_to 'Modifier', edit_player_path(@player), :class=>"pull-right card-link btn btn-info d-none d-lg-block"
      