config/routes.rb
Rails.application.routes.draw do
  
  get "wizard/new_game", to: "wizard#game_step_0", as: "new_game_wizard"
  post "wizard/create_new_game", to: "wizard#game_step_1", as: "game_step_1"
  get "games/:id/round/:round_number", to: "games#edit_round", as: "game_edit_round"
  post "games/:id/round/:round_number", to: "games#save_round", as: "game_save_round"
  get "games/:id/recap", to: "games#recap", as: "game_recap"
  get "games/:id/compute_results", to: "games#compute_results", as: "game_compute_results"
  get "games/:id/spectator", to: "games#spectator", as: "game_spectator"
  post "games/:id/save_graph", to: "games#save_graph", as: "game_save_graph"
  post "trophies/recompute_all", to: "trophies#recalculate_all_trophies_for_all_games", as: "trophies_recompute_all"
  get "trophies/matrice", to: "trophies#matrice", as: "matrice"
  
  get "calendar", to:"games#calendar", as: "calendar"
  
  resources :performances
  get "trophies/records", to: "trophies#records_index", as: "records_index"
  resources :trophies
  resources :scores
  resources :rounds
  resources :games
  resources :players
  
  get "dashboard", to: "home#dashboard", as: "dashboard"

  root to: 'home#index'
  
  devise_for :users
  
end

app/models/trophy.rb
class Trophy < ApplicationRecord
  has_many :performances
  scope :active, -> { where(active: true) }

  enum positive: { pasbien: 4, neutre: 5, bien: 6}
  enum only_once: { une_seule_fois: 1, plusieurs_fois: 0}
  
  
  def self.unlock_victory(game, player)
    t=Trophy.find_by_technical_name('victory')
    if Result.for_game_and_player(game, player).ranking==1
        p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
        p.save
        return true
    else
        Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
        return false
    end
  end
  
  def self.unlock_one_point_winner(game, player)
    t=Trophy.find_by_technical_name('one_point_winner')
    
    score_premier= Result.where(:game=>game, :ranking=>1).try(:first).try(:total_score) || 1000
    score_second= Result.where(:game=>game, :ranking=>2).try(:first).try(:total_score) || 1000
    diff=score_premier-score_second
    if Result.for_game_and_player(game, player).ranking==1 && diff==1
        p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
        p.save
        return true
    else
        Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
        return false
    end
  end
  
  def self.unlock_modjo(game, player)
    t=Trophy.find_by_technical_name('modjo')
    Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
    if player.scores_in_game(game).pluck(:value).max > 9
        Performance.create(:game=>game,:player=>player, :trophy=>t)
        return true
    end
    return false
  end
  
  def self.unlock_after_2_pm(game,player)
    t=Trophy.find_by_technical_name('after_2_pm')
    Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
    h=game.rounds.order(:created_at).last.created_at.time.hour
    if h >= 12 && h<14 
        Performance.create(:game=>game,:player=>player, :trophy=>t)
        return true
    end
    return false
  end
  
  def self.unlock_boring(game, player)
    t=Trophy.find_by_technical_name('boring')
    p_result=Result.for_game_and_player(game, player)
    p2_total_score=game.results.where(:ranking=>2).first.try(:total_score)
    if p2_total_score.nil?
      Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
      return false
    end
    if p_result.ranking==1 && (p_result.total_score - p2_total_score > 14)
        p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
        p.save
        return true
    else
        Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
        return false
    end
  end
  
  def self.unlock_dix_cafes(game, player)
    t=Trophy.find_by_technical_name("dix_cafes")
    return false if t.nil?
    if Performance.where(:player=>player, :trophy=>t).blank? && player.nb_payed_coffees_all_time > 10
        Performance.create(:game=>game,:player=>player, :trophy=>t)
        return true
    else
        return false
    end
  end
  def self.unlock_cent_cafes(game, player)
    t=Trophy.find_by_technical_name("cent_cafes")
    return false if t.nil?
    if Performance.where(:player=>player, :trophy=>t).blank? && player.nb_payed_coffees_all_time > 100
        Performance.create(:game=>game,:player=>player, :trophy=>t)
        return true
    else
        return false
    end
  end
  
  def self.unlock_back_2_back(game, player)
    t=Trophy.find_by_technical_name('back_2_back')
    Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
    if Result.for_game_and_player(game, player).ranking==1
      prevgame=player.games.order(:created_at).where("created_at < ?",game.created_at).try(:last)
      if Result.for_game_and_player(prevgame, player).try(:ranking)==1
        return false if Performance.where(:game=>prevgame,:player=>player, :trophy=>t).present?
        p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
        p.save
        return true
      end
    end
    return false
  end  
  def self.unlock_petit_chelem(game, player)
    t=Trophy.find_by_technical_name('petit_chelem')
    Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
    if Result.for_game_and_player(game, player).ranking==1
      nb_echecs=game.scores.where(:player=>player).where("VALUE < 0").count
      if nb_echecs==1
        p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
        p.save
        return true
      end
    end
    return false
  end
  
  
  def self.unlock_perfect(game, player)
    t=Trophy.find_by_technical_name('perfect')
    Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
    if Result.for_game_and_player(game, player).ranking==1
      nb_echecs=game.scores.where(:player=>player).where("VALUE < 0").count
      if nb_echecs==0
        p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
        p.save
        return true
      end
    end
    return false
  end
  
  def self.unlock_back_3_back(game, player)
    t=Trophy.find_by_technical_name('back_3_back')
    Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
    if Result.for_game_and_player(game, player).ranking==1
      prevgame=player.games.order(:created_at).where("created_at < ?",game.created_at).try(:last)
      # raise prevgame.inspect
      if Result.for_game_and_player(prevgame, player).try(:ranking)==1
        prevgame2=player.games.order(:created_at).where("created_at < ?", prevgame.created_at).try(:last)
        if Result.for_game_and_player(prevgame2, player).try(:ranking)==1
          p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
          p.save
          return true
        end
      end
    end
    return false
  end
  
  
  { "bienvenue" => 2, "debutant" => 10, "competent" => 30, "expert" => 50, "master" => 100 }.each do |techname, threshold|
    define_singleton_method("unlock_#{techname}") do |game, player|
      t=Trophy.find_by_technical_name(techname)
      return false if t.nil?
      if Performance.where(:player=>player, :trophy=>t).present?
          # il a deja le trophée
          return false
      elsif player.results.count==threshold
          Performance.create(:game=>game,:player=>player, :trophy=>t)
          return true
      else
          return false
      end
    end
  end
    
  def self.unlock_ca_partage(game, player)
    t=Trophy.find_by_technical_name('ca_partage')
    puts "======>"+Result.where(:game=>game, :ranking => 1).count.inspect 
    if Result.for_game_and_player(game, player).ranking==1 && (Result.where(:game=>game, :ranking => 1).count > 1) 
        p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
        p.save
        return true
    else
        Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
        return false
    end
  end
    
  def self.unlock_tout_ca_pour_ca(game,player)
    t=Trophy.find_by_technical_name('tout_ca_pour_ca')
    if Result.for_game_and_player(game, player).total_score==0
        p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
        p.save
        return true
    else
        Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
        return false
    end
  end
  
  def self.unlock_jacques_mayol(game,player)
    t=Trophy.find_by_technical_name('jacques_mayol')
    if game.scores.where(:player=>player).pluck(:tmp_total).any?(&:positive?) == false
      p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
      p.save
      return true
    else
      Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
      return false
    end
  end
  def self.unlock_chalumeau(game,player)
    t=Trophy.find_by_technical_name('chalumeau')
    ar=game.scores.where(:player=>player).pluck(:value)
    chalum=false
    ar.each_cons(5) { |cons| chalum=cons.all?{|val| val == -1}if chalum==false } 
    if chalum
      p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
      p.save
      return true
    else
      Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
      return false
    end
  end
  
  def self.unlock_carambolage(game,player)
    return false if game.players.count<4
    t=Trophy.find_by_technical_name('carambolage')
    car=false
    game.rounds.each do |r|
      car=true if r.scores.pluck(:value).all?{|sc| sc < 1}
    end
    if car
      p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
      p.save
      return true
    else
      Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
      return false
    end
  end 
  
  def self.unlock_glacons(game,player)
    return false unless game.losers.include? player
    return false if game.losers.count > 1
    t=Trophy.find_by_technical_name('glacons')
    loser_result=Result.for_game_and_player(game, player)
    second_loser_result=Result.where(:game=>game, :ranking=>loser_result.ranking-1).first
    if (loser_result.nil? || second_loser_result.nil?)
      puts "##################"
      puts "###TRUC BIZARRE###"
      puts "##################"
      puts "sur la partie #{game.id}"
      puts "dans la boucle du joueur #{player.name}"
      puts "LOSER RESULT est NIL" if loser_result.nil?
      puts "SECOND LOSER RESULT est NIL" if second_loser_result.nil?
      puts "##################"
      return false 
    end
    if (second_loser_result.total_score - loser_result.total_score) >=15
      p=Performance.where(:game=>game,:player=>player, :trophy=>t).first_or_initialize
      p.save
      return true
    else
      Performance.where(:game=>game,:player=>player, :trophy=>t).destroy_all
      return false
    end
  end
  
  def self.unlock_collectionneur(game, player)
    t=Trophy.find_by_technical_name('collectionneur')
    if player.performances.pluck(:trophy_id).uniq.count >= 10

app/controllers/trophies_controller.rb
class TrophiesController < ApplicationController
  before_action :set_trophy, only: [:show, :edit, :update, :destroy]

  # GET /trophies
  # GET /trophies.json
  def index
    @trophies = Trophy.all
  end

  def records_index
    @records = Record.all
  end

  # GET /trophies/1
  # GET /trophies/1.json
  def show
  end

  def matrice
    @trophies=Trophy.active
  end

  # GET /trophies/new
  def new
    @trophy = Trophy.new
  end

  # GET /trophies/1/edit
  def edit
  end

  # POST /trophies
  # POST /trophies.json
  def create
    @trophy = Trophy.new(trophy_params)

    respond_to do |format|
      if @trophy.save
        format.html { redirect_to @trophy, notice: 'Trophy was successfully created.' }
        format.json { render :show, status: :created, location: @trophy }
      else
        format.html { render :new }
        format.json { render json: @trophy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trophies/1
  # PATCH/PUT /trophies/1.json
  def update
    respond_to do |format|
      if @trophy.update(trophy_params)
        format.html { redirect_to @trophy, notice: 'Trophy was successfully updated.' }
        format.json { render :show, status: :ok, location: @trophy }
      else
        format.html { render :edit }
        format.json { render json: @trophy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trophies/1
  # DELETE /trophies/1.json
  def destroy
    @trophy.destroy
    respond_to do |format|
      format.html { redirect_to trophies_url, notice: 'Trophy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  def recalculate_all_trophies_for_all_games
    Game.all.each do |g|
      g.compute_performances
      puts "======= GAME recalculé    : #{g.title} =========="
    end
    
    flash[:info] = "Tous les calculs sont terminés."
   
    redirect_to trophies_path
    
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trophy
      @trophy = Trophy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trophy_params
      params.require(:trophy).permit(:name, :technical_name, :description, :active, :positive, :only_once, :gifurl)
    end
end

app/helpers/trophies_helper.rb
module TrophiesHelper
end

app/views/trophies/_form.html.haml
= form_for @trophy, :class=>"form" do |f|
  - if @trophy.errors.any?
    #error_explanation
      %h2= "#{pluralize(@trophy.errors.count, "error")} prohibited this trophy from being saved:"
      %ul
        - @trophy.errors.full_messages.each do |message|
          %li= message
  .col-6.offset-3
    .field
      = f.label :name
      = f.text_field :name,  :class=>"form-control"
    
    -unless @trophy.active
      .field
        = f.label :technical_name
        = f.text_field :technical_name,  :class=>"form-control"
        
    .form-group
      .checkbox-inline
        = f.check_box :active
        = f.label "Active"
        
    .form-group
      .checkbox-inline
        = f.label :positive 
        = f.select :positive, Trophy.positives.keys
    
    .form-group
      .checkbox-inline
        = f.label :positive, "Combien de fois peut-on l'obtenir ?" 
        = f.select :only_once, Trophy.only_onces.keys
        
    .field
      = f.label :description
      = f.text_area :description,  :class=>"form-control"
    %br/
      
    .field
      = f.label :gifurl, "GIF URL"
      = f.text_field :gifurl,  :class=>"form-control"
    %br/
    .actions
      = f.submit 'Enregistrer', :class=>"btn btn-primary"
    %hr

app/views/trophies/edit.html.haml
.card.card-body
  %h4.card-title Modification de trophy
  
  %p.card-text
    = render 'form'
    
  .flex-row
    = link_to 'Voir', @trophy
    \|
    = link_to 'Retour', trophies_path

app/views/trophies/index.html.haml
.card.border-dark
  .card-header.bg-dark.text-white
    %h4.card-title.text-center Trophées
  
  .card-body
  
    = link_to 'Nouveau Trophée', new_trophy_path, :class=>"card-link btn btn-sm btn-primary"
    = link_to 'Matrice joueurs/trophées', matrice_path, :class=>"card-link btn btn-sm btn-info"
    = link_to 'Records du monde', records_index_path, :class=>" card-link btn btn-sm btn-warning"
    %table.table.table-striped#trophies_table
      %thead
        %tr.bg-dark.text-white
          %th.nosort
          %th Nom
          %th Description
          %th Positif
          %th Activé
          %th.nosort
    
      %tbody.text-dark
        - @trophies.each do |trophy|
          %tr
            %td 
              -if trophy.gifurl.present?
                =image_tag trophy.gifurl, :height=>"70px"
            %td= trophy.name
            // %td= trophy.technical_name
            %td= trophy.description
            %td.text-center
              - case trophy.positive
                -when "bien" 
                  %small.badge.badge-sm.badge-success Bon
                -when "neutre" 
                  %small.badge.badge-sm.badge-secondary Neutre
                -when "pasbien" 
                  %small.badge.badge-sm.badge-danger Mauvais
            %td{:class=>trophy.active ? "table-success" : "table-secondary"}= trophy.active ? "Ouaip" : "Nan"
            %td
              .btn-group
                = link_to trophy, :class=>"btn btn-secondary" do
                  =fa_icon 'eye'
                = link_to edit_trophy_path(trophy), :class=>"btn btn-secondary" do
                  =fa_icon 'edit'
                -unless trophy.active
                  = link_to trophy, method: :delete, data: { confirm: 'Etes-vous sur?' }, :class=>"btn btn-secondary" do
                    =fa_icon 'trash'
  .card-footer
    
    
    = button_to trophies_recompute_all_path, :class=>"d-none d-lg-block card-link pull-right btn-sm btn btn-danger", 'data-disable-with' => fa_icon("spinner spin ").html_safe, data: { confirm: 'Etes-vous sur? Cliquez uniquement si vous comprenez ce que vous faites.' } do
      =fa_icon 'warning'
      Tout recalculer pour toutes les parties
      =fa_icon 'warning'
  :javascript
      $(document).ready( function () {
        $('#trophies_table').DataTable({
          'paging': true,
          'pageLength': 20,
          'lengthChange': false,
          "info": true,
          'aoColumnDefs': [{
            'bSortable': false,
            'aTargets': ['nosort']
          }]
        });
      } );

app/views/trophies/matrice.html.haml
.card.border-dark
  .card-header.bg-dark.text-white
    %h4.card-title.text-center Matrice Trophées/Joueurs
  
  .card-body.p-0
    %table.table.table-bordered.table-hover#trophies_table.border-dark.border.border-2.p-0.m-0
      %thead.border-dark
        %tr.bg-dark.text-white
          %th.bg-dark.border-dark.border.border-bottom-0
          -Player.all.order(:id).each do |p|
            %th.text-center.border-dark.border.border-bottom-0
              .p-0.m-0
                -if p.avatar.present?
                  =image_tag "animals/#{p.avatar}.png", size: "30"
                -else
                  =image_tag "animals/sheep-1.png", size: "30"
              =link_to p.name, p, :class=>"text-white"

      %tbody.text-dark.border-dark
        - @trophies.each do |trophy|
          %tr.border-dark.border
            %td.bg-dark.text-white.border.border-left-0.border-right-0.border-secondary{:style=>"width:20%;"}
              =link_to trophy.name, trophy, :class=>"text-white"
            -widz=80/Player.all.count
            -Player.all.order(:id).each do |p|
            
              -case nb=p.count_trophy(trophy)
              -when 0
                %td.bg-white{:style=>"width:#{widz}%;"}
              -when 1
                %td.bg-info.text-center.text-dark{:style=>"width:#{widz}%;"}
                  =fa_icon 'trophy'
              -else
                %td.bg-info.text-center{:style=>"width:#{widz}%;"}
                  .badge.badge-dark.text-white
                    =nb
                    =fa_icon 'trophy'
                  

app/views/trophies/new.html.haml
.card.card-body
  %h4.card-title Nouveau trophy
  %p.card-text 

    = render 'form'


  .flex-row
    = link_to 'Retour', trophies_path

app/views/trophies/records_index.html.haml
.card.border-dark
  .card-header.bg-dark.text-white
    %h4.card-title.text-center Records du monde
  
  .card-body.bg-dark
    -@records.order(:name).each_slice(5) do |r_slice|
      .row
        -r_slice.each do |r|
          .col.text-center.pb-2.pt-3.border-info
            .card{:style=>"border-color:Gold"}
              .card-header{:style=>"background-color:Gold"}
                %b=r.name
                %br
                =fa_icon 'medal 3x'
              
              .card-body.bg-dark{:style=>"min-height:140px;"}
                -if r.player.present?
                  .text-center
                    -if r.player.avatar.present?
                      =image_tag "animals/#{r.player.avatar}.png", size: "40"
                    -else
                      =image_tag "animals/sheep-1.png", size: "40"
                    %h2
                      .badge{:style=>"color:Gold"}=r.player.name
                  %small.text-secondary.text-center
                    -if r.game.present?
                      =link_to r.value, game_recap_path(r.game) , :class=>"text-warning"
                    -else
                      =r.value
                -else
                  %h3.text-secondary Personne
            %br
      
    
    // = button_to trophies_recompute_all_path, :class=>"d-none d-lg-block card-link pull-right btn-sm btn btn-danger", 'data-disable-with' => fa_icon("spinner spin ").html_safe, data: { confirm: 'Etes-vous sur? Cliquez uniquement si vous comprenez ce que vous faites.' } do
    //   =fa_icon 'warning'
    //   Tout recalculer pour toutes les parties
    //   =fa_icon 'warning'

app/views/trophies/show.html.haml
.card.border-dark.mb-3
  .card-header.bg-dark.text-center.text-white
    %h2.pt-2
      =fa_icon "trophy"
      %b= @trophy.name
      %br
      
    .pull-left
      %small.badge.badge-sm.badge-secondary=@trophy.technical_name
      
      -case @trophy.active
        -when true
          %small.badge.badge-sm.badge-success Activé
        -when false 
          %small.badge.badge-sm.badge-danger Pas activé

    .pull-right

      - case @trophy.positive
        -when "bien" 
          %small.badge.badge-sm.badge-success Positif
        -when "neutre" 
          %small.badge.badge-sm.badge-secondary Neutre
        -when "pasbien" 
          %small.badge.badge-sm.badge-danger Négatif
      - case @trophy.only_once
        -when "une_seule_fois" 
          %small.badge.badge-sm.badge-info Ne peut s'obtenir qu'une seule fois
        -when "plusieurs_fois" 
          %small.badge.badge-sm.badge-info Peut s'obtenir plusieurs fois
        -else
          %small.badge.badge-sm.badge-danger C'est chelou appelez Max
  .card-body
    %p.card-text.text-center.px-5
      -if @trophy.gifurl.present?
        =image_tag @trophy.gifurl, :height=>"200px"
        %br/
      = @trophy.description
  .card-footer.bg-dark.text-white
    .pt-3.pb-0.h5 
      Détenu par :
      -if @trophy.performances.blank?
        %span.text-muted
          Personne
          ¯\_(ツ)_/¯
      -else
        .row.performances_div.px-2.pt-2
          -@trophy.performances.group(:player).count.each do |p, count|
            -perf_games_html=capture_haml do
              -perfs_games=Game.where(:id=>@trophy.performances.where(:player=>p).pluck(:game_id))
              -perfs_games.each do |g|
                =link_to "#{g.title}", game_recap_path(g), :class=>"text-info", :style=>"text-decoration:none"
                ="<br/>" unless perfs_games.last==g
                
            .col-sm-12.col-md-4.m-0.p-0
  
              -if count>1
                .card.bg-dark.text-center.m-2
  
                  .card-body
                    =link_to p, :class=>"text-white" do
                      .text-center
                        -if p.avatar.present?
                          =image_tag "animals/#{p.avatar}.png", size: "40"
                        -else
                          =image_tag "animals/sheep-1.png", size: "40"
  
                      =p.name
                    %br
                      %span.badge.badge-info.text-dark{"data-html"=>"true","data-template"=>'<div class="popover popover-secondary " role="tooltip"><div class="arrow "></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>', "data-content" => perf_games_html.html_safe, "data-toggle" => "popover", "data-placement" => "bottom", "data-trigger" => "focus", :role => "button", :tabindex => "0"}
                        =count
              -else
                .card.bg-dark.text-center.m-2
                  .card-body
                    =link_to p, :class=>"text-white" do
                      .text-center
                        -if p.avatar.present?
                          =image_tag "animals/#{p.avatar}.png", size: "40"
                        -else
                          =image_tag "animals/sheep-1.png", size: "40"
  
                      =p.name
                    %br
                    %small.text-info=perf_games_html.html_safe
                
          
    

.flex-row
  = link_to 'Retour', :back, :class=>"btn btn-secondary d-lg-none"
  = link_to 'Retour', trophies_path, :class=>"btn btn-secondary d-none d-lg-inline-block"
  = link_to 'Modifier', edit_trophy_path(@trophy), :class=>"pull-right card-link btn btn-info d-none d-lg-block"