config/routes.rb
Rails.application.routes.draw do
  
  get "wizard/new_game", to: "wizard#game_step_0", as: "new_game_wizard"
  post "wizard/create_new_game", to: "wizard#game_step_1", as: "game_step_1"
  get "games/:id/round/:round_number", to: "games#edit_round", as: "game_edit_round"
  post "games/:id/round/:round_number", to: "games#save_round", as: "game_save_round"
  get "games/:id/recap", to: "games#recap", as: "game_recap"
  get "games/:id/compute_results", to: "games#compute_results", as: "game_compute_results"
  get "games/:id/spectator", to: "games#spectator", as: "game_spectator"
  post "games/:id/save_graph", to: "games#save_graph", as: "game_save_graph"
  post "trophies/recompute_all", to: "trophies#recalculate_all_trophies_for_all_games", as: "trophies_recompute_all"
  get "trophies/matrice", to: "trophies#matrice", as: "matrice"
  
  get "calendar", to:"games#calendar", as: "calendar"
  
  resources :performances
  get "trophies/records", to: "trophies#records_index", as: "records_index"
  resources :trophies
  resources :scores
  resources :rounds
  resources :games
  resources :players
  
  get "dashboard", to: "home#dashboard", as: "dashboard"

  root to: 'home#index'
  
  devise_for :users
  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "apple-touch-fullscreen"}/
    %meta#extViewportMeta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no", :name => "viewport"}/
    
    %link{:href => "/favicon.ico", :rel => "shortcut icon", :type => "image/x-icon"}/
    %link{:href => "/favicon.ico", :rel => "icon", :type => "image/x-icon"}/

    %link{:href => "apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "apple-touch-icon-57x57.png", :rel => "apple-touch-icon", :sizes => "57x57"}/
    %link{:href => "apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "apple-touch-icon-76x76.png", :rel => "apple-touch-icon", :sizes => "76x76"}/
    %link{:href => "apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/
    %link{:href => "apple-touch-icon-120x120.png", :rel => "apple-touch-icon", :sizes => "120x120"}/
    %link{:href => "apple-touch-icon-144x144.png", :rel => "apple-touch-icon", :sizes => "144x144"}/
    %link{:href => "apple-touch-icon-152x152.png", :rel => "apple-touch-icon", :sizes => "152x152"}/
    %link{:href => "apple-touch-icon-180x180.png", :rel => "apple-touch-icon", :sizes => "180x180"}/
    %link{:href => "apple-touch-icon-180x180.png", :rel => "icon", :sizes => "180x180" }/
    
    
    %link{:href => "iphone5_splash.png", :media => "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)", :rel => "apple-touch-startup-image"}/
    %link{:href => "iphone6_splash.png", :media => "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)", :rel => "apple-touch-startup-image"}/
    %link{:href => "iphoneplus_splash.png", :media => "(device-width: 621px) and (device-height: 1104px) and (-webkit-device-pixel-ratio: 3)", :rel => "apple-touch-startup-image"}/
    %link{:href => "iphonex_splash.png", :media => "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)", :rel => "apple-touch-startup-image"}/
    %link{:href => "ipad_splash.png", :media => "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)", :rel => "apple-touch-startup-image"}/
    %link{:href => "ipadpro1_splash.png", :media => "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)", :rel => "apple-touch-startup-image"}/
    %link{:href => "ipadpro2_splash.png", :media => "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)", :rel => "apple-touch-startup-image"}/
    
    
    
    %title TheFullMontee
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => "reload"
    = javascript_include_tag 'application', 'data-turbolinks-track' => "reload"
    = csrf_meta_tags
  
  
    %link{:href => "https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css", :rel => "stylesheet"}/
    
    %script(src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js")
    
    %script(src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js")
    %link{:rel =>"stylesheet",  :href => "https://use.fontawesome.com/releases/v5.2.0/css/all.css", :integrity =>"sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ", :crossorigin=>"anonymous"}


    %link{:href => "https://fonts.googleapis.com/css?family=Lato", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Muli", :rel => "stylesheet"}/

    = javascript_tag "window._token = '#{form_authenticity_token}'" 
  %body#page-top{:style=>""}

    / Navigation
    - if user_signed_in?
      %nav#mainNav.navbar.navbar-expand-lg.navbar-light.static-top
        .container
          =link_to root_path, :class=>" d-none d-lg-block navbar-brand js-scroll-trigger" do
            =image_tag "tfmlogo.png", :alt=>"TheFullMontee", "height"=>"60px", :class=>"pt-1"
          
          =link_to root_path, :class=>" d-inline-block d-lg-none navbar-brand js-scroll-trigger", :style=>"width:60%" do
            =image_tag "tfmlogo.png", :alt=>"TheFullMontee", :width=>"100%"
          %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
            Menu
            %i.fa.fa-bars
          .d-block.d-lg-none.collapse.navbar-collapse
            #navbarResponsive.collapse.navbar-collapse
              %ul.navbar-nav.ml-auto
              
                %li.nav-item.d-block.d-lg-none
                  %h6
                    %strong= link_to 'Parties', games_path, :class=>"nav-link text-white pull-right"
                // %li.nav-item= link_to 'Rounds', rounds_path, :class=>"nav-link"
                // %li.nav-item= link_to 'Scores', scores_path, :class=>"nav-link"
                %li.nav-item.d-block.d-lg-none
                  %h6
                    %strong= link_to 'Joueurs', players_path, :class=>"nav-link text-white pull-right"
                %li.nav-item.d-block.d-lg-none
                  %h6
                    %strong= link_to 'Tableau de bord', dashboard_path, :class=>"nav-link text-white pull-right"
                    
                // %li.nav-item= link_to 'Déconnexion', destroy_user_session_path, :method=>'delete', :class=>"nav-link"
              
          #navbar_big.d-none.d-lg-block
            %ul.navbar-nav.ml-auto
            
              %li.nav-item= link_to 'Tableau de bord', dashboard_path, :class=>"nav-link"
              %li.nav-item= link_to 'Parties', games_path, :class=>"nav-link"
              // %li.nav-item= link_to 'Rounds', rounds_path, :class=>"nav-link"
              // %li.nav-item= link_to 'Scores', scores_path, :class=>"nav-link"
              %li.nav-item= link_to 'Joueurs', players_path, :class=>"nav-link"
              %li.nav-item= link_to 'Trophées', trophies_path, :class=>"nav-link"
              // %li.nav-item= link_to 'Déconnexion', destroy_user_session_path, :method=>'delete', :class=>"nav-link"
              
    %section
      .container{:style=>"-webkit-overflow-scrolling: touch;"}
        -flash.each do |key, value| 
          %div{:class=>"alert alert-#{key}"}
            = value

        =yield
    :javascript
      $(function () {
        $('[data-toggle="popover"]').popover()
        $('.popover-dismiss').popover({
          trigger: 'focus'
        })
      })
      var a=document.getElementsByTagName("a");
      for(var i=0;i<a.length;i++)
      {
          a[i].onclick=function()
          {
            if (this.getAttribute("id")!="targetblank"){
              window.location=this.getAttribute("href");
              return false
            }
          }
      }
      function replaceclick(t){
        console.log("lets replace click");
          window.location=t.getAttribute("data-to-href");
          return false
      }
      $.extend( $.fn.dataTable.defaults, {
          searching: true,
          ordering:  true,
          paging: true,
          lengthChange: false,
          info: true,
          autoWidth: true,
          order:[],
          columnDefs: [ {
              targets  : 'no-sort',
              orderable : false,
          }],
          language: {
              processing:     "Traitement en cours...",
              search:         "Rechercher&nbsp;:",
              lengthMenu:    "Afficher _MENU_ éléments",
              info:           "Affichage des éléments _START_ à _END_  (sur un total de _TOTAL_)",
              infoEmpty:      "Aucun élément à afficher",
              infoFiltered:   "(filtré sur _MAX_ éléments au total)",
              infoPostFix:    "",
              loadingRecords: "Chargement en cours...",
              zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
              emptyTable:     "Aucune donnée disponible dans le tableau",
              paginate: {
                  first:      "Premier",
                  previous:   "Pr&eacute;c&eacute;dent",
                  next:       "Suivant",
                  last:       "Dernier"
              },
              aria: {
                  sortAscending:  ": activer pour trier la colonne par ordre croissant",
                  sortDescending: ": activer pour trier la colonne par ordre décroissant"
              }
          }
      } );